config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :coins
  resources :portfolios
  root "portfolios#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    include Cryptocurrency
    
    has_many :coin_users
    has_many :users, through: :coin_users
end

app/models/coin_user.rb
class CoinUser < ApplicationRecord
  belongs_to :coin
  belongs_to :user
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    belongs_to :user, optional: true
    validates :symbol, length: { in: 3..4, message: "%{value} is not a valid size. Must be 3 or 4 characters" }
    validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :portfolio
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name])
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]

  # GET /coins
  # GET /coins.json
  def index
    @gainers = Coin.new.top10Gainers
    @losers = Coin.new.top10Losers
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:name, :symbol, :price, :change24hr, :volume24hr)
    end

    def coin_gainers
      coin = Cryptocurrency.new
      coin.top10Gainers
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Coin.new.update_portfolio_data(Portfolio.all.where(user_id: current_user.id))
    @portfolio  = Portfolio.new
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)
    @portfolio.user_id = current_user.id 
    respond_to do |format|
      if @portfolio.save
        @portfolio.coin_id = Coin.new.search(@portfolio[:symbol])
        @portfolio.save
        # @portfolio.user_id = current_user.id
        # byebug()
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :show }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:symbol, :quantity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :change24hr %>
    <%= form.text_field :change24hr %>
  </div>

  <div class="field">
    <%= form.label :volume24hr %>
    <%= form.text_field :volume24hr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Price</th>
      <th>Change24hr</th>
      <th>Volume24hr</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% table.each do |k, v| %>
      <tr>
        <td><%= v["name"] %></td>
        <td><%= v["symbol"] %></td>
        <td><%= v["price"] %></td>
        <td><%= number_to_percentage((v["quotes"]["USD"]["percent_change_24h"]), precision: 2) %></td>
        <td><%= number_to_currency(v["quotes"]["USD"]["volume_24h"]) %></td>
      </tr>
    <% end %>
  </tbody> 
</table>

app/views/coins/edit.html.erb
<h1>Editing Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coins</h1>

<!-- Renders the form and passes @gainers through as local variable 'table' -->
<%= render partial: "table", object: @gainers %>

<!-- Renders the form and passes @losers through as local variable 'table' -->
<%= render partial: "table", object: @losers %>




<%= link_to 'New Coin', new_coin_path %>

app/views/coins/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>



<div>
    <h2>Parameters</h2>
    <%= @params %>
</div>

<%= link_to 'Back', books_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coin.name %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @coin.symbol %>
</p>

<p>
  <strong>Price:</strong>
  <%= @coin.price %>
</p>

<p>
  <strong>Change24hr:</strong>
  <%= @coin.change24hr %>
</p>

<p>
  <strong>Volume24hr:</strong>
  <%= @coin.volume24hr %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Portfolio", root_path, class: "nav-item nav-link active" %>
        <%= link_to "Tracking", root_path, class: "nav-item nav-link active" %>
        <%= link_to "Movers", coins_path, class: "nav-item nav-link active" %>
        <%= link_to "Logout", destroy_user_session_path, class: "nav-item nav-link active", method: "delete" %>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeCoinMktCap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" if user_signed_in? %>
    
    <div class="container">
      <%= yield %>
    </div>
  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_new_coin.html.erb
<%= form_with model: portfolio, local: true do |form| %>
  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>
  <div class="field">
    <%= form.label :quantity %>
    <!-- Fix this later, so it can take decimals -->
    <%= form.number_field :quantity  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Price</th>
      <th>Change24hr</th>
      <th>Qunatity Held</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% table.each do |k, v| %>
      <tr>
        <td><%= v["name"] %></td>
        <td><%= v["symbol"] %></td>
        <td><%= number_to_currency(v["price"]) %></td>
        <td><%= number_to_percentage((v["change24h"]), precision: 2) %></td>
        <td><%= v["quantity"] %></td>
        
      </tr>
    <% end %>
  </tbody> 
</table>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<%= render partial: "table", object: @portfolios %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |k, v| %>
      <tr>
        <td><%= link_to 'Destroy', v, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render 'new_coin', portfolio: @portfolio %>

<%= link_to "Log Out", destroy_user_session_path, method: :delete %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Back', portfolios_path %>

<h1> NO LUCK </h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>